return {
	{ { "4" }, { { app = "Google Chrome", title = "4 - Google Chrome" } } },
	{ { "a" }, { { app = "Activity Monitor", title = "Activity Monitor – All Processes" } } },
	{ { "a", "n" }, { { app = "Anki", title = "User 1 - Anki" } } },
	{ { "b" }, { { app = "Bear", title = "Bear" } } },
	{ { "b", "b" }, { { app = "Bear", title = "vim to memo" } } },
	{ { "c" }, { { app = "Google Chrome", title = "calendar - Google Chrome" } } },
	{ { "f" }, { { app = "Finder", title = "Downloads" } } },
	{ { "g" }, { { app = "Google Chrome", title = "general - Google Chrome" } } },
	{ { "g", "c" }, { { app = "Google Chrome", title = "gchat - Google Chrome" } } },
	{ { "g", "l" }, { { app = "Google Chrome", title = "gleam - Google Chrome" } } },
	{ { "g", "m" }, { { app = "Google Chrome", title = "gmail - Google Chrome" } } },
	{ { "h" }, { { app = "iTerm2", title = "hs" } } },
	{ { "h", "c" }, { { app = "Hammerspoon", title = "Hammerspoon Console" } } },
	{ { "i" }, { { app = "iReal Pro", title = "Library" } } },
	{ { "l" }, { { app = "Google Chrome", title = "local - Google Chrome" } } },
	{ { "m", "e" }, { { app = "Google Chrome", title = "messages - Google Chrome" } } },
	{ { "m", "o" }, { { app = "Google Chrome", title = "monkey - Google Chrome" } } },
	{ { "o" }, { { app = "Obsidian", title = "Dogs & Owners - Obsidian Vault - Obsidian v0.15.9" } } },
	{ { "p", "l" }, { { app = "Google Chrome", title = "programming languages - Google Chrome" } } },
	{ { "r" }, { { app = "Google Chrome", title = "research - Google Chrome" } } },
	{ { "v", "v" }, { { app = "Google Chrome", title = "vim - Google Chrome" } } },
	{ { "w" }, { { app = "Google Chrome", title = "whatsapp - Google Chrome" } } },
	{ { "w", "e" }, { { app = "Google Chrome", title = "weather - Google Chrome" } } },
	{ { "x" }, { { app = "iTerm2", title = "python3 -m http.server 8002" } } },
}
